### ISSUE TITLE
maybe a bug

### ISSUE THREAD

**Issue by GYT0106** [Quplet/NoShieldDelay#7]
I am Chinese, please forgive me for not speaking English well
![屏幕截图 2024-08-09 225831](https://github.com/user-attachments/assets/3af3d31f-d9e6-42a4-967d-5edcf4944182)
[minecraft-exported-crash-info-2024-08-09T22-59-03.zip](https://github.com/user-attachments/files/16563477/minecraft-exported-crash-info-2024-08-09T22-59-03.zip)
[minecraft-exported-logs-2024-08-09T22-59-10.log](https://github.com/user-attachments/files/16563478/minecraft-exported-logs-2024-08-09T22-59-10.log)
I didn't know what file to upload, so I uploaded the file involving the logs, and the launcher showed a mod error, but I had tried reinstalling

**Comment by Quplet** [comment]
Repeat of #2, fixed with 1.0.1
